backend:
  name: github
  branch: main
  repo: digital-land/content-site # cms repo
  base_url: https://dl-cms-oauth-service.herokuapp.com # OAuth server
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "guidance"
    label: "Guidance pages"
    label_singular: "Guidance page"
    folder: "app/content/guidance"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
